/// <reference path="../exceptionless.ts" />
declare var jstz;
module exceptionless {
    export class TimeZoneUtil {
        constructor () { }

        public static setDefaultTimeZone(elementId: string) {
            var dropDown = $(elementId);
            if (jQuery.isEmptyObject(dropDown))
                return;

            if (dropDown.has(':selected').val() != 'Dateline Standard Time')
                return;

            var timeZoneName = TimeZoneUtil.getStandardTimeZoneName();
            if (!StringUtil.isNullOrEmpty(timeZoneName)) {
                var options = $(StringUtil.format('{elementId} option[value="{timeZoneName}"]', { elementId: elementId, timeZoneName: timeZoneName }));
                if (!jQuery.isEmptyObject(options)) {
                    dropDown.val(options.first().val()).prop("selected", "selected");
                    return;
                }
            }

            options = $(StringUtil.format("{elementId} option:contains('(UTC{offset})')", { elementId: elementId, offset: DateUtil.localTimeZoneOffset }));
            if (jQuery.isEmptyObject(options))
                return;

            dropDown.val(options.first().val()).prop("selected", "selected");
        }

        public static getStandardTimeZoneName(): string {
            var tz = jstz.determine();
            switch (tz.name()) {
                case 'Africa/Abidjan': return 'Greenwich Standard Time';
                case 'Africa/Accra': return 'Greenwich Standard Time';
                case 'Africa/Addis_Ababa': return 'E. Africa Standard Time';
                case 'Africa/Algiers': return 'Central Europe Standard Time';
                case 'Africa/Asmara': return 'E. Africa Standard Time';
                case 'Africa/Bamako': return 'Greenwich Standard Time';
                case 'Africa/Bangui': return 'W. Central Africa Standard Time';
                case 'Africa/Banjul': return 'Greenwich Standard Time';
                case 'Africa/Bissau': return 'Greenwich Standard Time';
                case 'Africa/Blantyre': return 'South Africa Standard Time';
                case 'Africa/Brazzaville': return 'W. Central Africa Standard Time';
                case 'Africa/Bujumbura': return 'South Africa Standard Time';
                case 'Africa/Cairo': return 'Egypt Standard Time';
                case 'Africa/Casablanca': return 'Greenwich Standard Time';
                case 'Africa/Ceuta': return 'Central Europe Standard Time';
                case 'Africa/Conakry': return 'Greenwich Standard Time';
                case 'Africa/Dakar': return 'Greenwich Standard Time';
                case 'Africa/Dar_es_Salaam': return 'E. Africa Standard Time';
                case 'Africa/Djibouti': return 'E. Africa Standard Time';
                case 'Africa/Douala': return 'W. Central Africa Standard Time';
                case 'Africa/El_Aaiun': return 'Greenwich Standard Time';
                case 'Africa/Freetown': return 'Greenwich Standard Time';
                case 'Africa/Gaborone': return 'South Africa Standard Time';
                case 'Africa/Harare': return 'South Africa Standard Time';
                case 'Africa/Johannesburg': return 'South Africa Standard Time';
                case 'Africa/Kampala': return 'E. Africa Standard Time';
                case 'Africa/Khartoum': return 'E. Africa Standard Time';
                case 'Africa/Kigali': return 'South Africa Standard Time';
                case 'Africa/Kinshasa': return 'W. Central Africa Standard Time';
                case 'Africa/Lagos': return 'W. Central Africa Standard Time';
                case 'Africa/Libreville': return 'W. Central Africa Standard Time';
                case 'Africa/Lome': return 'Greenwich Standard Time';
                case 'Africa/Luanda': return 'W. Central Africa Standard Time';
                case 'Africa/Lubumbashi': return 'South Africa Standard Time';
                case 'Africa/Lusaka': return 'South Africa Standard Time';
                case 'Africa/Malabo': return 'W. Central Africa Standard Time';
                case 'Africa/Maputo': return 'South Africa Standard Time';
                case 'Africa/Maseru': return 'South Africa Standard Time';
                case 'Africa/Mbabane': return 'South Africa Standard Time';
                case 'Africa/Mogadishu': return 'E. Africa Standard Time';
                case 'Africa/Monrovia': return 'Greenwich Standard Time';
                case 'Africa/Nairobi': return 'E. Africa Standard Time';
                case 'Africa/Ndjamena': return 'W. Central Africa Standard Time';
                case 'Africa/Niamey': return 'W. Central Africa Standard Time';
                case 'Africa/Nouakchott': return 'Greenwich Standard Time';
                case 'Africa/Ouagadougou': return 'Greenwich Standard Time';
                case 'Africa/Porto-Novo': return 'W. Central Africa Standard Time';
                case 'Africa/Sao_Tome': return 'Greenwich Standard Time';
                case 'Africa/Tripoli': return 'South Africa Standard Time';
                case 'Africa/Tunis': return 'Central Europe Standard Time';
                case 'Africa/Windhoek': return 'W. Central Africa Standard Time';
                case 'America/Adak': return 'Hawaiian Standard Time';
                case 'America/Anchorage': return 'Alaskan Standard Time';
                case 'America/Anguilla': return 'Atlantic Standard Time';
                case 'America/Antigua': return 'Atlantic Standard Time';
                case 'America/Araguaina': return 'E. South America Standard Time';
                case 'America/Argentina/Buenos_Aires': return 'Argentina Standard Time';
                case 'America/Argentina/Catamarca': return 'Argentina Standard Time';
                case 'America/Argentina/Cordoba': return 'Argentina Standard Time';
                case 'America/Argentina/Jujuy': return 'Argentina Standard Time';
                case 'America/Argentina/La_Rioja': return 'Argentina Standard Time';
                case 'America/Argentina/Mendoza': return 'Argentina Standard Time';
                case 'America/Argentina/Rio_Gallegos': return 'Argentina Standard Time';
                case 'America/Argentina/San_Juan': return 'Argentina Standard Time';
                case 'America/Argentina/San_Luis': return 'Argentina Standard Time';
                case 'America/Argentina/Tucuman': return 'Argentina Standard Time';
                case 'America/Argentina/Ushuaia': return 'Argentina Standard Time';
                case 'America/Aruba': return 'Atlantic Standard Time';
                case 'America/Asuncion': return 'Central Brazilian Standard Time';
                case 'America/Atikokan': return 'Eastern Standard Time';
                case 'America/Bahia': return 'E. South America Standard Time';
                case 'America/Barbados': return 'Atlantic Standard Time';
                case 'America/Belem': return 'E. South America Standard Time';
                case 'America/Belize': return 'Central Standard Time (Mexico)';
                case 'America/Blanc-Sablon': return 'Atlantic Standard Time';
                case 'America/Boa_Vista': return 'Central Brazilian Standard Time';
                case 'America/Bogota': return 'SA Pacific Standard Time';
                case 'America/Boise': return 'Mountain Standard Time';
                case 'America/Cambridge_Bay': return 'Mountain Standard Time';
                case 'America/Campo_Grande': return 'SA Western Standard Time';
                case 'America/Cancun': return 'Central Standard Time (Mexico)';
                case 'America/Caracas': return 'Newfoundland Standard Time';
                case 'America/Cayenne': return 'SA Eastern Standard Time';
                case 'America/Cayman': return 'Eastern Standard Time';
                case 'America/Chicago': return 'Central Standard Time';
                case 'America/Chihuahua': return 'Mountain Standard Time (Mexico)';
                case 'America/Costa_Rica': return 'Central Standard Time (Mexico)';
                case 'America/Cuiaba': return 'SA Western Standard Time';
                case 'America/Curacao': return 'Atlantic Standard Time';
                case 'America/Danmarkshavn': return 'Greenwich Standard Time';
                case 'America/Dawson': return 'Pacific Standard Time';
                case 'America/Dawson_Creek': return 'Mountain Standard Time';
                case 'America/Denver': return 'Mountain Standard Time';
                case 'America/Detroit': return 'Eastern Standard Time';
                case 'America/Dominica': return 'Atlantic Standard Time';
                case 'America/Edmonton': return 'Mountain Standard Time';
                case 'America/Eirunepe': return 'SA Pacific Standard Time';
                case 'America/El_Salvador': return 'Central Standard Time (Mexico)';
                case 'America/Fortaleza': return 'E. South America Standard Time';
                case 'America/Glace_Bay': return 'Atlantic Standard Time';
                case 'America/Godthab': return 'Greenland Standard Time';
                case 'America/Goose_Bay': return 'Atlantic Standard Time';
                case 'America/Grand_Turk': return 'Eastern Standard Time';
                case 'America/Grenada': return 'Atlantic Standard Time';
                case 'America/Guadeloupe': return 'Atlantic Standard Time';
                case 'America/Guatemala': return 'Central Standard Time (Mexico)';
                case 'America/Guayaquil': return 'SA Pacific Standard Time';
                case 'America/Guyana': return 'SA Western Standard Time';
                case 'America/Halifax': return 'Atlantic Standard Time';
                case 'America/Havana': return 'SA Pacific Standard Time';
                case 'America/Hermosillo': return 'Mountain Standard Time';
                case 'America/Indiana/Indianapolis': return 'Eastern Standard Time';
                case 'America/Indiana/Knox': return 'Central Standard Time';
                case 'America/Indiana/Marengo': return 'Eastern Standard Time';
                case 'America/Indiana/Petersburg': return 'Eastern Standard Time';
                case 'America/Indiana/Tell_City': return 'Central Standard Time';
                case 'America/Indiana/Vevay': return 'Eastern Standard Time';
                case 'America/Indiana/Vincennes': return 'Eastern Standard Time';
                case 'America/Indiana/Winamac': return 'Eastern Standard Time';
                case 'America/Inuvik': return 'Mountain Standard Time';
                case 'America/Iqaluit': return 'Eastern Standard Time';
                case 'America/Jamaica': return 'Eastern Standard Time';
                case 'America/Juneau': return 'Alaskan Standard Time';
                case 'America/Kentucky/Louisville': return 'Eastern Standard Time';
                case 'America/Kentucky/Monticello': return 'Eastern Standard Time';
                case 'America/La_Paz': return 'SA Western Standard Time';
                case 'America/Lima': return 'SA Pacific Standard Time';
                case 'America/Los_Angeles': return 'Pacific Standard Time';
                case 'America/Maceio': return 'E. South America Standard Time';
                case 'America/Managua': return 'Central Standard Time (Mexico)';
                case 'America/Manaus': return 'Central Brazilian Standard Time';
                case 'America/Martinique': return 'Atlantic Standard Time';
                case 'America/Mazatlan': return 'Mountain Standard Time (Mexico)';
                case 'America/Menominee': return 'Central Standard Time (Mexico)';
                case 'America/Merida': return 'Central Standard Time (Mexico)';
                case 'America/Mexico_City': return 'Central Standard Time (Mexico)';
                case 'America/Miquelon': return 'Greenland Standard Time';
                case 'America/Moncton': return 'Atlantic Standard Time';
                case 'America/Monterrey': return 'Central Standard Time (Mexico)';
                case 'America/Montevideo': return 'Montevideo Standard Time';
                case 'America/Montreal': return 'Eastern Standard Time';
                case 'America/Montserrat': return 'Atlantic Standard Time';
                case 'America/Nassau': return 'Eastern Standard Time';
                case 'America/New_York': return 'Eastern Standard Time';
                case 'America/Nipigon': return 'Eastern Standard Time';
                case 'America/Nome': return 'Alaskan Standard Time';
                case 'America/Noronha': return 'Mid-Atlantic Standard Time';
                case 'America/North_Dakota/Center': return 'Central Standard Time';
                case 'America/North_Dakota/New_Salem': return 'Central Standard Time';
                case 'America/Panama': return 'Eastern Standard Time';
                case 'America/Pangnirtung': return 'Eastern Standard Time';
                case 'America/Paramaribo': return 'SA Eastern Standard Time';
                case 'America/Phoenix': return 'US Mountain Standard Time';
                case 'America/Port_of_Spain': return 'Atlantic Standard Time';
                case 'America/Port-au-Prince': return 'Eastern Standard Time';
                case 'America/Porto_Velho': return 'Central Brazilian Standard Time';
                case 'America/Puerto_Rico': return 'Atlantic Standard Time';
                case 'America/Rainy_River': return 'Central Standard Time';
                case 'America/Rankin_Inlet': return 'Central Standard Time';
                case 'America/Recife': return 'E. South America Standard Time';
                case 'America/Regina': return 'Central Standard Time';
                case 'America/Resolute': return 'Eastern Standard Time';
                case 'America/Rio_Branco': return 'SA Pacific Standard Time';
                case 'America/Santiago': return 'SA Western Standard Time';
                case 'America/Santo_Domingo': return 'Atlantic Standard Time';
                case 'America/Sao_Paulo': return 'E. South America Standard Time';
                case 'America/Scoresbysund': return 'Azores Standard Time';
                case 'America/St_Johns': return 'Newfoundland Standard Time';
                case 'America/St_Kitts': return 'Atlantic Standard Time';
                case 'America/St_Lucia': return 'Atlantic Standard Time';
                case 'America/St_Thomas': return 'Atlantic Standard Time';
                case 'America/St_Vincent': return 'Atlantic Standard Time';
                case 'America/Swift_Current': return 'Central Standard Time (Mexico)';
                case 'America/Tegucigalpa': return 'Central Standard Time (Mexico)';
                case 'America/Thule': return 'Atlantic Standard Time';
                case 'America/Thunder_Bay': return 'Eastern Standard Time';
                case 'America/Tijuana': return 'Pacific Standard Time (Mexico)';
                case 'America/Toronto': return 'Eastern Standard Time';
                case 'America/Tortola': return 'Atlantic Standard Time';
                case 'America/Vancouver': return 'Pacific Standard Time';
                case 'America/Whitehorse': return 'Pacific Standard Time';
                case 'America/Winnipeg': return 'Central Standard Time';
                case 'America/Yakutat': return 'Alaskan Standard Time';
                case 'America/Yellowknife': return 'Mountain Standard Time';
                case 'Antarctica/Casey': return 'W. Australia Standard Time';
                case 'Antarctica/Davis': return 'SE Asia Standard Time';
                case 'Antarctica/DumontDUrville': return 'E. Australia Standard Time';
                case 'Antarctica/Mawson': return 'Central Asia Standard Time';
                case 'Antarctica/McMurdo': return 'New Zealand Standard Time';
                case 'Antarctica/Palmer': return 'SA Western Standard Time';
                case 'Antarctica/Rothera': return 'SA Eastern Standard Time';
                case 'Antarctica/Syowa': return 'E. Africa Standard Time';
                case 'Antarctica/Vostok': return 'Central Asia Standard Time';
                case 'Asia/Aden': return 'Arabic Standard Time';
                case 'Asia/Almaty': return 'Central Asia Standard Time';
                case 'Asia/Amman': return 'Jordan Standard Time';
                case 'Asia/Anadyr': return 'New Zealand Standard Time';
                case 'Asia/Aqtau': return 'West Asia Standard Time';
                case 'Asia/Aqtobe': return 'West Asia Standard Time';
                case 'Asia/Ashgabat': return 'West Asia Standard Time';
                case 'Asia/Baghdad': return 'Arabic Standard Time';
                case 'Asia/Bahrain': return 'Arabic Standard Time';
                case 'Asia/Baku': return 'Azerbaijan Standard Time';
                case 'Asia/Bangkok': return 'SE Asia Standard Time';
                case 'Asia/Beirut': return 'Middle East Standard Time';
                case 'Asia/Bishkek': return 'Central Asia Standard Time';
                case 'Asia/Brunei': return 'North Asia East Standard Time';
                case 'Asia/Choibalsan': return 'Yakutsk Standard Time';
                case 'Asia/Chongqing': return 'China Standard Time';
                case 'Asia/Colombo': return 'Sri Lanka Standard Time';
                case 'Asia/Damascus': return 'Middle East Standard Time';
                case 'Asia/Dhaka': return 'N. Central Asia Standard Time';
                case 'Asia/Dili': return 'Korea Standard Time';
                case 'Asia/Dubai': return 'Arabian Standard Time';
                case 'Asia/Dushanbe': return 'West Asia Standard Time';
                case 'Asia/Gaza': return 'Middle East Standard Time';
                case 'Asia/Harbin': return 'China Standard Time';
                case 'Asia/Ho_Chi_Minh': return 'SE Asia Standard Time';
                case 'Asia/Hong_Kong': return 'Malay Peninsula Standard Time';
                case 'Asia/Hovd': return 'SE Asia Standard Time';
                case 'Asia/Irkutsk': return 'North Asia East Standard Time';
                case 'Asia/Jakarta': return 'SE Asia Standard Time';
                case 'Asia/Jayapura': return 'Korea Standard Time';
                case 'Asia/Jerusalem': return 'Middle East Standard Time';
                case 'Asia/Kabul': return 'Afghanistan Standard Time';
                case 'Asia/Kamchatka': return 'Fiji Standard Time';
                case 'Asia/Karachi': return 'West Asia Standard Time';
                case 'Asia/Kashgar': return 'China Standard Time';
                case 'Asia/Katmandu': return 'Nepal Standard Time';
                case 'Asia/Kolkata': return 'India Standard Time';
                case 'Asia/Krasnoyarsk': return 'North Asia Standard Time';
                case 'Asia/Kuala_Lumpur': return 'Malay Peninsula Standard Time';
                case 'Asia/Kuching': return 'Malay Peninsula Standard Time';
                case 'Asia/Kuwait': return 'Arabic Standard Time';
                case 'Asia/Macau': return 'China Standard Time';
                case 'Asia/Magadan': return 'Central Pacific Standard Time';
                case 'Asia/Makassar': return 'Malay Peninsula Standard Time';
                case 'Asia/Manila': return 'Malay Peninsula Standard Time';
                case 'Asia/Muscat': return 'Arabian Standard Time';
                case 'Asia/Nicosia': return 'Middle East Standard Time';
                case 'Asia/Novosibirsk': return 'N. Central Asia Standard Time';
                case 'Asia/Omsk': return 'N. Central Asia Standard Time';
                case 'Asia/Oral': return 'Ekaterinburg Standard Time';
                case 'Asia/Phnom_Penh': return 'SE Asia Standard Time';
                case 'Asia/Pontianak': return 'SE Asia Standard Time';
                case 'Asia/Pyongyang': return 'Korea Standard Time';
                case 'Asia/Qatar': return 'Arabic Standard Time';
                case 'Asia/Qyzylorda': return 'N. Central Asia Standard Time';
                case 'Asia/Rangoon': return 'Myanmar Standard Time';
                case 'Asia/Riyadh': return 'Arabic Standard Time';
                case 'Asia/Sakhalin': return 'Vladivostok Standard Time';
                case 'Asia/Samarkand': return 'West Asia Standard Time';
                case 'Asia/Seoul': return 'Korea Standard Time';
                case 'Asia/Shanghai': return 'China Standard Time';
                case 'Asia/Singapore': return 'Malay Peninsula Standard Time';
                case 'Asia/Taipei': return 'China Standard Time';
                case 'Asia/Tashkent': return 'West Asia Standard Time';
                case 'Asia/Tbilisi': return 'Arabian Standard Time';
                case 'Asia/Tehran': return 'Iran Standard Time';
                case 'Asia/Thimphu': return 'N. Central Asia Standard Time';
                case 'Asia/Tokyo': return 'Tokyo Standard Time';
                case 'Asia/Ulaanbaatar': return 'North Asia East Standard Time';
                case 'Asia/Urumqi': return 'China Standard Time';
                case 'Asia/Vientiane': return 'SE Asia Standard Time';
                case 'Asia/Vladivostok': return 'Vladivostok Standard Time';
                case 'Asia/Yakutsk': return 'Yakutsk Standard Time';
                case 'Asia/Yekaterinburg': return 'Ekaterinburg Standard Time';
                case 'Asia/Yerevan': return 'Caucasus Standard Time';
                case 'Atlantic/Azores': return 'Azores Standard Time';
                case 'Atlantic/Bermuda': return 'Atlantic Standard Time';
                case 'Atlantic/Canary': return 'W. Europe Standard Time';
                case 'Atlantic/Cape_Verde': return 'Cape Verde Standard Time';
                case 'Atlantic/Faroe': return 'W. Europe Standard Time';
                case 'Atlantic/Madeira': return 'W. Europe Standard Time';
                case 'Atlantic/Reykjavik': return 'Greenwich Standard Time';
                case 'Atlantic/South_Georgia': return 'Mid-Atlantic Standard Time';
                case 'Atlantic/St_Helena': return 'Greenwich Standard Time';
                case 'Atlantic/Stanley': return 'Pacific SA Standard Time';
                case 'Australia/Adelaide': return 'Cen. Australia Standard Time';
                case 'Australia/Brisbane': return 'E. Australia Standard Time';
                case 'Australia/Broken_Hill': return 'Cen. Australia Standard Time';
                case 'Australia/Currie': return 'Tasmania Standard Time';
                case 'Australia/Darwin': return 'AUS Central Standard Time';
                case 'Australia/Eucla': return 'Cen. Australia Standard Time';
                case 'Australia/Hobart': return 'Tasmania Standard Time';
                case 'Australia/Lindeman': return 'AUS Eastern Standard Time';
                case 'Australia/Lord_Howe': return 'Central Pacific Standard Time';
                case 'Australia/Melbourne': return 'AUS Eastern Standard Time';
                case 'Australia/Perth': return 'W. Australia Standard Time';
                case 'Australia/Sydney': return 'AUS Eastern Standard Time';
                case 'CET': return 'Central Europe Standard Time';
                case 'CST6CDT': return 'Central Standard Time';
                case 'EET': return 'E. Europe Standard Time';
                case 'EST': return 'Eastern Standard Time';
                case 'EST5EDT': return 'Eastern Standard Time';
                case 'Etc/GMT': return 'GMT Standard Time';
                case 'Etc/UCT': return 'GMT Standard Time';
                case 'Etc/UTC': return 'GMT Standard Time';
                case 'Europe/Amsterdam': return 'W. Europe Standard Time';
                case 'Europe/Andorra': return 'Central Europe Standard Time';
                case 'Europe/Athens': return 'E. Europe Standard Time';
                case 'Europe/Belgrade': return 'Central Europe Standard Time';
                case 'Europe/Berlin': return 'W. Europe Standard Time';
                case 'Europe/Brussels': return 'Central European Standard Time';
                case 'Europe/Bucharest': return 'E. Europe Standard Time';
                case 'Europe/Budapest': return 'Central European Standard Time';
                case 'Europe/Chisinau': return 'E. Europe Standard Time';
                case 'Europe/Copenhagen': return 'Central European Standard Time';
                case 'Europe/Dublin': return 'GMT Standard Time';
                case 'Europe/Gibraltar': return 'Central European Standard Time';
                case 'Europe/Helsinki': return 'E. Europe Standard Time';
                case 'Europe/Istanbul': return 'E. Europe Standard Time';
                case 'Europe/Kaliningrad': return 'E. Europe Standard Time';
                case 'Europe/Kiev': return 'E. Europe Standard Time';
                case 'Europe/Lisbon': return 'W. Europe Standard Time';
                case 'Europe/London': return 'GMT Standard Time';
                case 'Europe/Luxembourg': return 'Central European Standard Time';
                case 'Europe/Madrid': return 'Central European Standard Time';
                case 'Europe/Malta': return 'Central European Standard Time';
                case 'Europe/Minsk': return 'E. Europe Standard Time';
                case 'Europe/Monaco': return 'Central European Standard Time';
                case 'Europe/Moscow': return 'Russian Standard Time';
                case 'Europe/Oslo': return 'Central European Standard Time';
                case 'Europe/Paris': return 'Central European Standard Time';
                case 'Europe/Prague': return 'Central European Standard Time';
                case 'Europe/Riga': return 'E. Europe Standard Time';
                case 'Europe/Rome': return 'W. Europe Standard Time';
                case 'Europe/Samara': return 'Caucasus Standard Time';
                case 'Europe/Simferopol': return 'E. Europe Standard Time';
                case 'Europe/Sofia': return 'E. Europe Standard Time';
                case 'Europe/Stockholm': return 'W. Europe Standard Time';
                case 'Europe/Tallinn': return 'E. Europe Standard Time';
                case 'Europe/Tirane': return 'Central European Standard Time';
                case 'Europe/Uzhgorod': return 'E. Europe Standard Time';
                case 'Europe/Vaduz': return 'W. Europe Standard Time';
                case 'Europe/Vienna': return 'Central European Standard Time';
                case 'Europe/Vilnius': return 'E. Europe Standard Time';
                case 'Europe/Volgograd': return 'Russian Standard Time';
                case 'Europe/Warsaw': return 'Central European Standard Time';
                case 'Europe/Zaporozhye': return 'E. Europe Standard Time';
                case 'Europe/Zurich': return 'Central European Standard Time';
                case 'HST': return 'Hawaiian Standard Time';
                case 'Indian/Antananarivo': return 'E. Africa Standard Time';
                case 'Indian/Chagos': return 'Central Asia Standard Time';
                case 'Indian/Christmas': return 'SE Asia Standard Time';
                case 'Indian/Cocos': return 'Myanmar Standard Time';
                case 'Indian/Comoro': return 'E. Africa Standard Time';
                case 'Indian/Kerguelen': return 'West Asia Standard Time';
                case 'Indian/Mahe': return 'Arabian Standard Time';
                case 'Indian/Maldives': return 'West Asia Standard Time';
                case 'Indian/Mauritius': return 'Azerbaijan Standard Time';
                case 'Indian/Mayotte': return 'E. Africa Standard Time';
                case 'Indian/Reunion': return 'Arabian Standard Time';
                case 'MET': return 'Central European Standard Time';
                case 'MST': return 'Mountain Standard Time';
                case 'MST7MDT': return 'US Mountain Standard Time';
                case 'Pacific/Apia': return 'Samoa Standard Time';
                case 'Pacific/Auckland': return 'New Zealand Standard Time';
                case 'Pacific/Chatham': return 'Fiji Standard Time';
                case 'Pacific/Easter': return 'Central Standard Time (Mexico)';
                case 'Pacific/Efate': return 'Central Pacific Standard Time';
                case 'Pacific/Enderbury': return 'Tonga Standard Time';
                case 'Pacific/Fakaofo': return 'Hawaiian Standard Time';
                case 'Pacific/Fiji': return 'Fiji Standard Time';
                case 'Pacific/Funafuti': return 'Fiji Standard Time';
                case 'Pacific/Galapagos': return 'Central Standard Time';
                case 'Pacific/Gambier': return 'Alaskan Standard Time';
                case 'Pacific/Guadalcanal': return 'Central Pacific Standard Time';
                case 'Pacific/Guam': return 'West Pacific Standard Time';
                case 'Pacific/Honolulu': return 'Hawaiian Standard Time';
                case 'Pacific/Johnston': return 'Hawaiian Standard Time';
                case 'Pacific/Kiritimati': return 'Tonga Standard Time';
                case 'Pacific/Kosrae': return 'Central Pacific Standard Time';
                case 'Pacific/Kwajalein': return 'Fiji Standard Time';
                case 'Pacific/Majuro': return 'Fiji Standard Time';
                case 'Pacific/Marquesas': return 'Pacific Standard Time (Mexico)';
                case 'Pacific/Midway': return 'Samoa Standard Time';
                case 'Pacific/Nauru': return 'Fiji Standard Time';
                case 'Pacific/Niue': return 'Samoa Standard Time';
                case 'Pacific/Norfolk': return 'Central Pacific Standard Time';
                case 'Pacific/Noumea': return 'Central Pacific Standard Time';
                case 'Pacific/Pago_Pago': return 'Samoa Standard Time';
                case 'Pacific/Palau': return 'Tokyo Standard Time';
                case 'Pacific/Pitcairn': return 'Pacific Standard Time';
                case 'Pacific/Ponape': return 'Central Pacific Standard Time';
                case 'Pacific/Port_Moresby': return 'West Pacific Standard Time';
                case 'Pacific/Rarotonga': return 'Hawaiian Standard Time';
                case 'Pacific/Saipan': return 'West Pacific Standard Time';
                case 'Pacific/Tahiti': return 'Hawaiian Standard Time';
                case 'Pacific/Tarawa': return 'Fiji Standard Time';
                case 'Pacific/Tongatapu': return 'Tonga Standard Time';
                case 'Pacific/Truk': return 'West Pacific Standard Time';
                case 'Pacific/Wake': return 'Fiji Standard Time';
                case 'Pacific/Wallis': return 'Fiji Standard Time';
                case 'PST8PDT': return 'Pacific Standard Time';
                case 'WET': return 'W. Europe Standard Time';
                case 'Etc/GMT+9': return 'Alaskan Standard Time';
                case 'Asia/Riyadh87': return 'Arabic Standard Time';
                case 'Asia/Riyadh88': return 'Arabic Standard Time';
                case 'Asia/Riyadh89': return 'Arabic Standard Time';
                case 'Etc/GMT+4': return 'Atlantic Standard Time';
                case 'Etc/GMT-10': return 'AUS Eastern Standard Time';
                case 'Etc/GMT-4': return 'Azerbaijan Standard Time';
                case 'Etc/GMT+1': return 'Azores Standard Time';
                case 'Etc/GMT-1': return 'Central Europe Standard Time';
                case 'Etc/GMT-11': return 'Central Pacific Standard Time';
                case 'Etc/GMT+6': return 'Central Standard Time';
                case 'Etc/GMT+12': return 'Dateline Standard Time';
                case 'Etc/GMT-2': return 'E. Europe Standard Time';
                case 'Etc/GMT+3': return 'E. South America Standard Time';
                case 'Etc/GMT+5': return 'Eastern Standard Time';
                case 'Etc/GMT-5': return 'Ekaterinburg Standard Time';
                case 'Etc/GMT+10': return 'Hawaiian Standard Time';
                case 'Etc/GMT+2': return 'Mid-Atlantic Standard Time';
                case 'Etc/GMT+7': return 'Mountain Standard Time';
                case 'Etc/GMT-6': return 'N. Central Asia Standard Time';
                case 'Etc/GMT-12': return 'New Zealand Standard Time';
                case 'Etc/GMT-7': return 'North Asia Standard Time';
                case 'Etc/GMT+8': return 'Pacific Standard Time';
                case 'Etc/GMT-3': return 'Russian Standard Time';
                case 'Etc/GMT+11': return 'Samoa Standard Time';
                case 'Etc/GMT-13': return 'Tonga Standard Time';
                case 'Etc/GMT-14': return 'Tonga Standard Time';
                case 'Etc/GMT-8': return 'W. Australia Standard Time';
                case 'Etc/GMT-9': return 'Yakutsk Standard Time';
            }
            return null;
        }
    }
}