---
ConnectionStrings:
#  Elasticsearch: http://localhost:9200
#  Cache: provider=redis;server="localhost,abortConnect=false"
#  MessageBus: provider=redis;server="localhost,abortConnect=false"
#  Metrics: provider=statsd;server=10.0.0.5
#  Queue: provider=redis;server="localhost,abortConnect=false"
#  Storage: ''
#  LDAP: ''
  OAuth: FacebookId=395178683904310;GitHubId=7ef1dd5bfbc4ccf7f5ef;GoogleId=809763155066-enkkdmt4ierc33q9cft9nf5d5c02h30q.apps.googleusercontent.com;MicrosoftId=000000004C137E8B;SlackId=34500115540.177239122322;

  # Base url for the ui used to build links in emails and other places.
BaseURL: https://dev.exceptionless.io

# Exceptionless Client Settings
ExceptionlessServerUrl: https://dev-api.exceptionless.io
InternalProjectId: 50ca6b2423d6c8493020b823

StripePublishableApiKey: pk_test_nStD8zuwsiyVjPhfxxxMEFeE