version: 2
updates:

- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  cooldown:
    default-days: 7

- package-ecosystem: "npm"
  directory: "/src/Exceptionless.Web/ClientApp"
  schedule:
    interval: "weekly"
  cooldown:
    default-days: 7
