FORMAT: 1A
HOST: http://api.exceptionless.com/api/v1

# Exceptionless
Discover errors in your .NET app you never knew were happening and use detailed error reports to squash them with ease. Make your app Exceptionless!

# Group Event
Events related resources of the **Events API**

## Event [/event]
### List all events for an organization(s) [GET]
+ Parameters
    + organizationId (optional, string, `537650f3b77efe23a47914f3`) ...The identifier of the organization Id.
    + after (optional, string, `100650f3b77efe23a4791400`) ... A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `after=obj_foo` in order to fetch the next page of the list.
    + limit = `10` (optional, number, `5`) ... A limit on the number of objects to be returned. Limit can range between 1 and 100 items.

+ Response 200 (application/json)

        [{
          "id": "537650f3b77efe23a47914f4", "message": "Jogging in park"
        }, {
          "id": "537650f3b77efe23a47914f5", "message": "Pick-up posters from post-office"
        }]

### Create a new event [POST]

+ Request (application/json)

        { "message": "Exceptionless is amazing!" }

+ Response 200 (application/json)

## Event [/stack/{stackId}/event]

### List all events for a given stack [GET]
+ Parameters
    + stackId (required, string, `537650f3b77efe23a47914f3`) ... The identifier of the stack.
    + before (optional, string, `100650f3b77efe23a4791400`) ... A cursor for use in pagination. `before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `before=obj_bar` in order to fetch the previous page of the list.
    + after (optional, string, `100650f3b77efe23a4791400`) ... A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `after=obj_foo` in order to fetch the next page of the list.
    + limit = `10` (optional, number, `5`) ... A limit on the number of objects to be returned. Limit can range between 1 and 100 items.

+ Response 200 (application/json)

        [{
          "id": "537650f3b77efe23a47914f4", "message": "Jogging in park"
        }, {
          "id": "537650f3b77efe23a47914f5", "message": "Pick-up posters from post-office"
        }]

## Event [/project/{projectId}/event]

### List all events for a given project [GET]
+ Parameters
    + projectId (required, string, `537650f3b77efe23a47914f3`) ... The identifier of the project.
    + before (optional, string, `100650f3b77efe23a4791400`) ... A cursor for use in pagination. `before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `before=obj_bar` in order to fetch the previous page of the list.
    + after (optional, string, `100650f3b77efe23a4791400`) ... A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `after=obj_foo` in order to fetch the next page of the list.
    + limit = `10` (optional, number, `5`) ... A limit on the number of objects to be returned. Limit can range between 1 and 100 items.

+ Response 200 (application/json)

        [{
          "id": "537650f3b77efe23a47914f4", "message": "Jogging in park"
        }, {
          "id": "537650f3b77efe23a47914f5", "message": "Pick-up posters from post-office"
        }]


# Group Organization
Organization related resources of the **Organization API**

## Organization [/organization]

### List all organizations [GET]

+ Parameters
    + before (optional, string, `100650f3b77efe23a4791400`) ... A cursor for use in pagination. `before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `before=obj_bar` in order to fetch the previous page of the list.
    + after (optional, string, `100650f3b77efe23a4791400`) ... A cursor for use in pagination. `after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `after=obj_foo` in order to fetch the next page of the list.
    + limit = `10` (optional, number, `5`) ... A limit on the number of objects to be returned. Limit can range between 1 and 100 items.

+ Response 200 (application/json)

        [{
          "id": "537650f3b77efe23a47914f3", "name": "Acme"
        }, {
          "id": "537650f3b77efe23a47914f3", "name": "Acme Supply"
        }]

### Create a new organization [POST]
+ Request (application/json)

        { "name": "Acme" }

+ Response 201 (application/json)

        { "id": "537650f3b77efe23a47914f3", "name": "Acme" }

## Organization [/organization/{id}]

+ Parameters
    + id (required, string, `537650f3b77efe23a47914f3`) ... The identifier of the document to be updated.

### Retrieve an Organization [GET]
A single Organization object with all its details

+ Response 200 (application/json)
    + Body

            { "id": "537650f3b77efe23a47914f3", "name": "Acme" }

### Update an organization [PATCH]
+ Request (application/json)

        { "name": "Updated Acme" }

+ Response 200 (application/json)

        { "id": "537650f3b77efe23a47914f3", "name": "Updated Acme" }

### Remove an Organization [DELETE]
+ Response 204

## Organization [/organization/{id}/user/{email}]
+ Parameters
    + id (required, string, `537650f3b77efe23a47914f3`) ... The identifier of the document to be updated.
    + email (required, string, `noreply@exceptionless.com`) ... The email address of the user you wish to remove from your organization.

### Add new user [POST]
+ Response 200

### Remove user [DELETE]
+ Response 200

## Organization [/organization/{id}/data/{key}]

### Add key [POST]
+ Parameters
    + id (required, string, `537650f3b77efe23a47914f3`) ... The identifier of the document to be updated.
    + key (required, string, `zip-code`) ... A identifier of the data object.
    + value (required, string, `90210`) ... Any string value.

+ Response 200

### Remove key [DELETE]
+ Parameters
    + id (required, string, `537650f3b77efe23a47914f3`) ... The identifier of the document to be updated.
    + key (required, string, `zip-code`) ... A identifier of the data object.
    
+ Response 200

## Organization [/organization/check-name{?name}]

### Check for existing organization name [GET]
+ Parameters
    + name (required, string, `My Organization`) ... The organization name to check.

+ Response 404