@token = 5f8aT5j0M1SdWCMOiJKCrlDNHMI38LjCH4LTWqGp
@apiUrl = http://exceptionless.localtest.me:5000/api/v2
@projectId = 537650f3b77efe23a47914f4

###

POST {{apiUrl}}/auth/login
Content-Type: application/json

{
    "email": "test@exceptionless.io",
    "password": "tester"
}

# copy token result to @token above

###

GET {{apiUrl}}/users/me
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/organizations
Authorization: Bearer {{token}}

###

GET {{apiUrl}}/projects
Authorization: Bearer {{token}}

###

POST {{apiUrl}}/projects/{{projectId}}/events
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "messge": "Hello World!"
}

###

GET {{apiUrl}}/events
Authorization: Bearer {{token}}
