@apiUrl = http://localhost:5000/api/v2
@email = test@test.com
@password = tester

### create an account
# @name account

POST {{apiUrl}}/auth/signup
Content-Type: application/json

{
    "name": "Test Tester",
    "email": "{{email}}",
    "password": "{{password}}"
}

@token = {{account.response.body.$.token}}
@email = {{account.request.body.$.email}}
@password = {{account.request.body.$.password}}

### login to test account
# @name login

POST {{apiUrl}}/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

@token = {{login.response.body.$.token}}

### get current user info

GET {{apiUrl}}/users/me
Authorization: Bearer {{token}}

### get organizations

GET {{apiUrl}}/organizations
Authorization: Bearer {{token}}

### get projects
# @name projects

GET {{apiUrl}}/projects
Authorization: Bearer {{token}}

@projectId = {{projects.response.body.$[0].id}}

### post a sample JSON event

POST {{apiUrl}}/projects/{{projectId}}/events
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "message": "Hello World!"
}

### post a sample text event

POST {{apiUrl}}/projects/{{projectId}}/events
Authorization: Bearer {{token}}
Content-Type: text/plain

Hello World!

### get events

GET {{apiUrl}}/events
Authorization: Bearer {{token}}
