apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "exceptionless.fullname" . }}-collector
  labels:
    app: {{ template "exceptionless.name" . }}
    component: {{ template "exceptionless.fullname" . }}-collector
    tier: {{ template "exceptionless.fullname" . }}-api
    chart: {{ template "exceptionless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.collector.replicaCount }}
  selector:
    matchLabels:
      component: {{ template "exceptionless.fullname" . }}-collector
  template:
    metadata:
      labels:
        app: {{ template "exceptionless.name" . }}
        component: {{ template "exceptionless.fullname" . }}-collector
        tier: {{ template "exceptionless.fullname" . }}-api
        chart: {{ template "exceptionless.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ template "exceptionless.name" . }}-collector
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: 2Gi
              cpu: 500m
            limits:
              memory: 3Gi
              cpu: 3000m
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ template "exceptionless.fullname" . }}-config
          env:
            - name: RunJobsInProcess
              value: 'false'
            - name: EnableWebSockets
              value: 'false'
{{- if (empty .Values.storage.azureConnectionString) }}
          volumeMounts:
            - mountPath: "/app/storage"
              name: storage
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ template "exceptionless.fullname" . }}-storage
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "exceptionless.fullname" . }}-collector
  labels:
    app: {{ template "exceptionless.name" . }}
    component: {{ template "exceptionless.fullname" . }}-collector
    chart: {{ template "exceptionless.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: {{ template "exceptionless.fullname" . }}-collector

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "exceptionless.fullname" . }}-collector-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/cors-allow-headers: "DNT,Keep-Alive,User-Agent,If-Modified-Since,Cache-Control,Content-Type,Authorization,ETag,Link,v,X-Requested-With,X-Exceptionless-Client,X-Result-Count,X-RateLimit-Limit,X-RateLimit-Remaining,X-Exceptionless-ConfigVersion"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
  - hosts:
    - {{.Values.collector.domain}}
    secretName: {{ template "exceptionless.fullname" . }}-collector-tls
  rules:
  - host: {{.Values.collector.domain}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "exceptionless.fullname" . }}-collector
          servicePort: 80
