appMode: Staging
appScope: dev
app:
  image:
    repository: exceptionless/app-ci
  defaultDomain: dev-app.exceptionless.io
  domains:
    - dev-app.exceptionless.io
api:
  image:
    repository: exceptionless/api-ci
  defaultDomain: dev-collector.exceptionless.io
  domains:
    - dev-collector.exceptionless.io
jobs:
  image:
    repository: exceptionless/job-ci

config:
  EX_EnableSnapshotJobs: "false"
  EX_TestEmailAddress: "test@exceptionless.io"
  EX_Serilog__MinimumLevel__Default: "Information"

otel:
  enabled: false
