apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: ex-prod
  namespace: ex-prod
spec:
  terminationPolicy: DoNotTerminate
  clusterDef: redis
  topology: replication
  componentSpecs:
    - name: redis
      serviceVersion: "8.4.0"
      disableExporter: false
      replicas: 2
      resources:
        requests:
          cpu: "200m"
          memory: 256Mi
        limits:
          cpu: "400m"
          memory: 512Mi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: managed-csi-premium
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
    - name: redis-sentinel
      serviceVersion: "8.4.0"
      replicas: 3
      resources:
        requests:
          cpu: "100m"
          memory: 64Mi
        limits:
          cpu: "200m"
          memory: 128Mi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: managed-csi-premium
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
