global:
  cloud: aks
  clusterName: ex-k8s-v6
  deploymentEnvironment: prod
otelCollectorEndpoint: ingest.us.signoz.cloud:443
otelInsecure: false
presets:
  otlpExporter:
    enabled: true
  loggingExporter:
    enabled: false
  logsCollection:
    enabled: false
  resourceDetection:
    detectors:
      - azure
      - system
  prometheus:
    enabled: true
    scrapeInterval: 30s
    namespaceScoped: false
    namespaces:
      - ex-prod
    scrapeConfigs:
      - job_name: elasticsearch
        static_configs:
          - targets:
              - es-exporter-prometheus-elasticsearch-exporter.ex-prod:9108
otelAgent:
  config:
    exporters:
      otlp/elastic:
        endpoint: http://apm.elastic-system.svc:8200
        tls:
          insecure: true
    processors:
      filter/drop_unused_metrics:
        error_mode: ignore
        metrics:
          metric:
            - 'name == "http.client.request.duration"'
            - 'name == "http.client.request.time_in_queue"'
            - 'name == "http.client.connection.duration"'
            - 'name == "http.client.open_connections"'
            - 'name == "http.client.active_requests"'
            - 'name == "dns.lookup.duration"'
            - 'name == "kestrel.connection.duration"'
            - 'name == "aspnetcore.authentication.authenticate.duration"'
            - 'name == "aspnetcore.routing.match_attempts"'
            - 'name == "dotnet.exceptions"'
            - 'name == "dotnet.gc.collections"'
            - 'name == "dotnet.gc.last_collection.heap.size"'
            - 'name == "dotnet.gc.last_collection.heap.fragmentation.size"'
            - 'name == "dotnet.process.cpu.time"'
            - 'name == "foundatio.lock.wait.time"'
            - 'name == "ex.posts.size"'
            - 'name == "ex.events.parse.jsoneventparserplugin"'
            - 'name == "ex.events.field.count"'
            - 'name == "ex.eventpipeline.markascriticalaction"'
      filter/drop_cache_spans:
        error_mode: ignore
        traces:
          span:
            - 'attributes["db.system"] == "redis" and status.code != STATUS_CODE_ERROR and (resource.attributes["service.name"] == "exceptionless-web" or resource.attributes["service.name"] == "job-event-posts")'
            - 'name == "Message: EntityChanged"'
    service:
      pipelines:
        traces:
          processors: [filter/drop_cache_spans, batch]
          exporters: [otlp, otlp/elastic]
        metrics:
          processors: [filter/drop_unused_metrics, batch]
          exporters: [otlp, otlp/elastic]
