global:
  cloud: aks
  clusterName: ex-k8s-v6
  deploymentEnvironment: prod
otelCollectorEndpoint: ingest.us.signoz.cloud:443
otelInsecure: false
presets:
  otlpExporter:
    enabled: true
  loggingExporter:
    enabled: false
  logsCollection:
    enabled: false
  resourceDetection:
    detectors:
      - azure
      - system
  prometheus:
    enabled: true
    scrapeInterval: 30s
    namespaceScoped: false
    namespaces:
      - ex-prod
    scrapeConfigs:
      - job_name: elasticsearch
        static_configs:
          - targets:
              - es-exporter-prometheus-elasticsearch-exporter.ex-prod:9108
otelAgent:
  config:
    exporters:
      otlp/elastic:
        endpoint: http://apm.elastic-system.svc:8200
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          exporters: [otlp, otlp/elastic]
        metrics:
          exporters: [otlp, otlp/elastic]
