<script lang="ts">
    import ErrorMessage from '$comp/ErrorMessage.svelte';
    import Loading from '$comp/Loading.svelte';
    import { H3, Muted } from '$comp/typography';
    import * as Avatar from '$comp/ui/avatar';
    import * as Form from '$comp/ui/form';
    import { Input } from '$comp/ui/input';
    import { Separator } from '$comp/ui/separator';
    import { applyServerSideErrors } from '$features/shared/validation';
    import { getMeQuery, mutateUser } from '$features/users/api.svelte';
    import { getGravatarFromCurrentUser } from '$features/users/gravatar.svelte';
    import { UpdateUser } from '$features/users/models';
    import { ProblemDetails } from "@exceptionless/fetchclient";
    import { toast } from 'svelte-sonner';
    import { defaults, superForm } from 'sveltekit-superforms';
    import SuperDebug from 'sveltekit-superforms';
    import { classvalidatorClient } from 'sveltekit-superforms/adapters';
    import { debounce } from 'throttle-debounce';

    let toastId = $state<number|string>();
    const userResponse = getMeQuery();
    const gravatar = getGravatarFromCurrentUser(userResponse);
    const updateUser = mutateUser({
        get id() {
            return userResponse.data?.id;
        }
    });

    const form = superForm(defaults(userResponse.data ?? {}, classvalidatorClient(UpdateUser)), {
        onError() {
            toastId = toast.error('An error occurred while saving your full name.');
        },
        async onUpdate({ form, result }) {
            if (!form.valid) {
                return;
            }

            toast.dismiss(toastId);
            try {
                form.data = await updateUser.mutateAsync(form.data);
                toastId = toast.success('Account updated successfully.');
            } catch (error: unknown) {
                if (error instanceof ProblemDetails) {
                    result.status = error.status ?? 500;
                    applyServerSideErrors(form, error);
                }

                throw error;
            }
        },
        SPA: true,
        validators: classvalidatorClient(UpdateUser)
    });

    $effect(() => {
        if (userResponse.isSuccess && !$submitting) {
            form.reset({ data: userResponse.data });
        }
    });

    const { enhance, form: formData, message, submit, submitting, tainted } = form;
    const debouncedSubmit = debounce(1000, submit);
</script>

<div class="space-y-6">
    <div>
        <H3>Account</H3>
        <Muted>Manage your account settings and set e-mail preferences.</Muted>
    </div>
    <Separator />

    <Avatar.Root class="h-24 w-24" title="Profile Image">
        {#await gravatar.src}
            <Avatar.Fallback><Loading /></Avatar.Fallback>
        {:then src}
            <Avatar.Image alt="gravatar" {src} />
        {/await}
        <Avatar.Fallback>{gravatar.initials}</Avatar.Fallback>
    </Avatar.Root>
    <Muted>Your avatar is generated by requesting a Gravatar image with the email address below.</Muted>

    <SuperDebug data={$tainted} />
    <SuperDebug data={$formData} />
    <form use:enhance>
        <ErrorMessage message={$message}></ErrorMessage>
        <Form.Field {form} name="full_name">
            <Form.Control let:attrs>
                <Form.Label>Full Name</Form.Label>
                <Input {...attrs} bind:value={$formData.full_name} placeholder="Full Name" autocomplete="name" required oninput={debouncedSubmit} />
            </Form.Control>
            <Form.Description />
            <Form.FieldErrors />
        </Form.Field>
        <!-- <Form.Field {form} name="email_address">
            <Form.Control let:attrs>
                <Form.Label>Email</Form.Label>
                <Input {...attrs} bind:value={$formData.email_address} placeholder="Enter email address" autocomplete="email" required />
            </Form.Control>
            <Form.Description />
            <Form.FieldErrors />
        </Form.Field> -->
        <!-- <Form.Button>
            {#if $submitting}
                <Loading class="mr-2" variant="secondary"></Loading> Saving...
            {:else}
                Save
            {/if}
        </Form.Button> -->
    </form>
</div>
