@apiUrl = http://localhost:5200/api/v2
@email = test@localhost
@password = tes

### Login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Signup
POST {{apiUrl}}/auth/signup
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "name": "test"
}

### Signup with token
POST {{apiUrl}}/auth/signup
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}",
  "name": "test"
}

### OAuth Login
POST {{apiUrl}}/auth/google
Content-Type: application/json

{
    "code": "code",
    "clientId": "clientId",
    "redirectUri": "http://localhost",
}
