@apiUrl = http://localhost:7110/api/v2
@email = admin@exceptionless.test
@password = tester
@clientToken = LhhP1C9gijpSKCslHHCvwdSIz298twx271nTest
@projectId = 537650f3b77efe23a47914f4
@referenceId = ref123456
@sessionId = 12345

### login to test account
# @name login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

###

@token = {{login.response.body.$.token}}

### List recent events
# @name allEvents
GET {{apiUrl}}/events?limit=10&sort=-date
Authorization: Bearer {{token}}

###
@eventId = {{allEvents.response.body.$[0].id}}

### By Id
GET {{apiUrl}}/events/{{eventId}}
Authorization: Bearer {{token}}

### Count open events with monthly aggregations
GET {{apiUrl}}/events/count?aggregations=date:(date~month+cardinality:stack+sum:count~1)+cardinality:stack+terms:(first+@include:true)+sum:count~1&filter=(status:open+OR+status:regressed)
Authorization: Bearer {{token}}

### Post Custom Event
POST {{apiUrl}}/events?access_token={{clientToken}}
Content-Type: application/json

{
  "type": "404",
  "source": "GET /Print",
  "message": null,
  "geo": "40,-70",
  "value": 1,
  "reference_id": "{{referenceId}}",
  "session_id": "{{sessionId}}",
  "data": {
    "number": 1,
    "decimal": 1.1,
    "string": "test",
    "boolean": false,
    "@user": {
      "identity": "My-User-Identity"
    },
    "@user_description": {
      "email_address": "{{email}}",
      "description": "my custom description"
    }
  }
}

### Add user feedback to the submitted event
POST {{apiUrl}}/events/by-ref/{{referenceId}}/user-description?access_token={{clientToken}}
Content-Type: application/json

{
  "email_address": "{{email}}",
  "description": "testing reference id"
}

### List project sessions (requires a paid plan)
GET {{apiUrl}}/projects/{{projectId}}/events/sessions?mode=summary&limit=10&sort=-date
Authorization: Bearer {{token}}

### Get the events in a session
GET {{apiUrl}}/projects/{{projectId}}/events/sessions/{{sessionId}}?mode=summary
Authorization: Bearer {{token}}
