@apiUrl = http://localhost:5200/api/v2
@email = test@localhost
@password = tester

### login to test account
# @name login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

@token = {{login.response.body.$.token}}

### Get Current User
# @name currentUser
GET {{apiUrl}}/users/me
Authorization: Bearer {{token}}

###
@userId = {{currentUser.response.body.$.id}}

### Delete By User Id
DELETE {{apiUrl}}/users/{{userId}}
Authorization: Bearer {{token}}

### Delete Current User
DELETE {{apiUrl}}/users/me
Authorization: Bearer {{token}}

### Unverify Email Addresses
POST {{apiUrl}}/users/unverify-email-address
Authorization: Bearer {{token}}
Content-Type: text/plain

noreply@localhost,
test@localhost
