@apiUrl = http://localhost:5200/api/v2
@email = test@localhost
@password = tester
@projectId = 537650f3b77efe23a47914f4

### login to test account
# @name login
POST {{apiUrl}}/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###

@token = {{login.response.body.$.token}}

### Get Test Payloads
GET {{apiUrl}}/webhooks/test
Authorization: Bearer {{token}}

### Post
# @name newWebhook
POST {{apiUrl}}/webhooks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "project_id": "{{projectId}}",
  "url": "https://localhost",
  "event_types": ["NewError", "CriticalError", "NewEvent", "CriticalEvent", "StackRegression", "StackPromoted"]
}

###

@webhookId = {{newWebhook.response.body.$.id}}

### Get By Project Id
GET {{apiUrl}}/projects/{{projectId}}/webhooks
Authorization: Bearer {{token}}

### Get By Id
GET {{apiUrl}}/webhooks/{{webhookId}}
Authorization: Bearer {{token}}

### Delete
DELETE {{apiUrl}}/webhooks/{{webhookId}}
Authorization: Bearer {{token}}

### Subscribe (Internal)
POST {{apiUrl}}/webhooks/subscribe
Authorization: Bearer {{token}}
Content-Type: application/json

{ "target_url": "https://hooks.zapier.com/localhost", "event": "NewError" }

### Unsubscribe (Internal)
POST {{apiUrl}}/webhooks/unsubscribe
Authorization: Bearer {{token}}
Content-Type: application/json

{ "target_url": "https://hooks.zapier.com/localhost" }
