using System.Diagnostics;
using Exceptionless.Core.Models;
using Exceptionless.Core.Plugins.EventParser;
using Exceptionless.Core.Validation;
using Xunit;

namespace Exceptionless.Tests.Validation;

public sealed class EventValidatorTests : TestWithServices
{
    private const string ValidObjectId = "123456789012345678901234";
    private readonly PersistentEvent _benchmarkEvent;
    private readonly MiniValidationValidator _validator;

    public EventValidatorTests(ITestOutputHelper output) : base(output)
    {
        _validator = GetService<MiniValidationValidator>();

        string path = Path.Combine("..", "..", "..", "Search", "Data", "event1.json");
        var parserPluginManager = GetService<EventParserPluginManager>();
        var events = parserPluginManager.ParseEvents(File.ReadAllText(path), 2, "exceptionless/2.0.0.0");
        _benchmarkEvent = events[0];
    }

    private PersistentEvent CreateValidEvent()
    {
        return new PersistentEvent
        {
            Id = ValidObjectId,
            OrganizationId = ValidObjectId,
            ProjectId = ValidObjectId,
            StackId = ValidObjectId,
            Type = Event.KnownTypes.Error,
            Date = DateTimeOffset.Now
        };
    }


    [Fact]
    public async Task Validate_WhenRunningBenchmark_CompletesInReasonableTime()
    {
        // Arrange
        const int iterations = 10000;
        var sw = Stopwatch.StartNew();

        // Act
        for (int i = 0; i < iterations; i++)
        {
            var (isValid, errors) = await _validator.ValidateAsync(_benchmarkEvent);
            Assert.True(isValid);
        }

        sw.Stop();

        // Assert
        _logger.LogInformation("Time: {Duration:g}, Avg: ({AverageTickDuration:g}ticks | {AverageDuration}ms)", sw.Elapsed, sw.ElapsedTicks / iterations, sw.ElapsedMilliseconds / iterations);
    }

    [Fact]
    public async Task Validate_WhenIdIsValidObjectId_ReturnsSuccess()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Id = ValidObjectId;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Fact]
    public async Task Validate_WhenIdIsNull_ReturnsSuccess()
    {
        // Arrange — Id is auto-generated by repo, null means "not yet assigned"
        var ev = CreateValidEvent();
        ev.Id = null!;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData("1234567890123456789012345")]
    [InlineData("invalid-id")]
    [InlineData("")]
    public async Task Validate_WhenIdIsInvalid_ReturnsError(string id)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Id = id;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(PersistentEvent.Id)));
    }

    [Fact]
    public async Task Validate_WhenOrganizationIdIsValidObjectId_ReturnsSuccess()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.OrganizationId = ValidObjectId;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData("1234567890123456789012345")]
    [InlineData("invalid-id")]
    [InlineData("")]
    [InlineData(null)]
    public async Task Validate_WhenOrganizationIdIsInvalid_ReturnsError(string? organizationId)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.OrganizationId = organizationId!;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(PersistentEvent.OrganizationId)));
    }

    [Fact]
    public async Task Validate_WhenProjectIdIsValidObjectId_ReturnsSuccess()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.ProjectId = ValidObjectId;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData("1234567890123456789012345")]
    [InlineData("invalid-id")]
    [InlineData("")]
    [InlineData(null)]
    public async Task Validate_WhenProjectIdIsInvalid_ReturnsError(string? projectId)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.ProjectId = projectId!;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(PersistentEvent.ProjectId)));
    }

    [Fact]
    public async Task Validate_WhenStackIdIsValidObjectId_ReturnsSuccess()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.StackId = ValidObjectId;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData("1234567890123456789012345")]
    [InlineData("invalid-id")]
    [InlineData("")]
    [InlineData(null)]
    public async Task Validate_WhenStackIdIsInvalid_ReturnsError(string? stackId)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.StackId = stackId!;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(PersistentEvent.StackId)));
    }

    [Fact]
    public async Task Validate_WhenTagIsValid_ReturnsSuccess()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Tags ??= new TagSet();
        ev.Tags.Add("1");

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    public async Task Validate_WhenTagIsEmpty_ReturnsError(string? tag)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Tags ??= new TagSet();
        ev.Tags.Add(tag);

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
    }

    [Fact]
    public async Task Validate_WhenTagExceedsMaxLength_ReturnsError()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Tags ??= new TagSet();
        ev.Tags.Add(new string('a', 256));

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    public async Task ValidateAsync_WhenTagIsEmpty_ReturnsError(string? tag)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Tags ??= new TagSet();
        ev.Tags.Add(tag);

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("1234567890123456")]
    public async Task Validate_WhenReferenceIdIsValid_ReturnsSuccess(string? referenceId)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.ReferenceId = referenceId;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Fact]
    public async Task Validate_WhenReferenceIdIsTooShort_ReturnsError()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.ReferenceId = "1234567";

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
    }

    [Fact]
    public async Task Validate_WhenReferenceIdIsTooLong_ReturnsError()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.ReferenceId = new string('1', 321);

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
    }

    [Theory]
    [InlineData(-60d)]
    [InlineData(0d)]
    [InlineData(60d)]
    public async Task Validate_WhenDateIsWithinRange_ReturnsSuccess(double minutes)
    {
        // Arrange
        var date = DateTimeOffset.Now.AddMinutes(minutes);
        var ev = CreateValidEvent();
        ev.Date = date;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        _logger.LogInformation(date + " " + isValid + " " + String.Join(" ", errors.SelectMany(e => e.Value)));
        Assert.True(isValid);
    }

    [Fact]
    public async Task Validate_WhenDateIsMinValue_ReturnsError()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Date = DateTimeOffset.MinValue;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
    }

    [Fact]
    public async Task Validate_WhenDateIsTooFarInFuture_ReturnsError()
    {
        // Arrange
        var date = DateTimeOffset.Now.AddMinutes(61);
        var ev = CreateValidEvent();
        ev.Date = date;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        _logger.LogInformation(date + " " + isValid + " " + String.Join(" ", errors.SelectMany(e => e.Value)));
        Assert.False(isValid);
    }

    [Theory]
    [InlineData(Event.KnownTypes.Error)]
    [InlineData(Event.KnownTypes.FeatureUsage)]
    [InlineData(Event.KnownTypes.Log)]
    [InlineData(Event.KnownTypes.NotFound)]
    [InlineData(Event.KnownTypes.SessionEnd)]
    [InlineData(Event.KnownTypes.Session)]
    public async Task Validate_WhenTypeIsValid_ReturnsSuccess(string type)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Type = type;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Fact]
    public async Task Validate_WhenTypeExceedsMaxLength_ReturnsError()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Type = new string('x', 101);

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    public async Task Validate_WhenTypeIsNullOrEmpty_ReturnsError(string? type)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Type = type!;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(PersistentEvent.Type)));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("Valid message")]
    public async Task Validate_WhenMessageIsValid_ReturnsSuccess(string? message)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Message = message;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Fact]
    public async Task Validate_WhenMessageIsEmpty_ReturnsError()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Message = String.Empty;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(PersistentEvent.Message)));
    }

    [Fact]
    public async Task Validate_WhenMessageExceedsMaxLength_ReturnsError()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Message = new string('x', 2001);

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(PersistentEvent.Message)));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("Valid source")]
    public async Task Validate_WhenSourceIsValid_ReturnsSuccess(string? source)
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Source = source;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Fact]
    public async Task Validate_WhenSourceIsEmpty_ReturnsError()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Source = String.Empty;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(PersistentEvent.Source)));
    }

    [Fact]
    public async Task Validate_WhenSourceExceedsMaxLength_ReturnsError()
    {
        // Arrange
        var ev = CreateValidEvent();
        ev.Source = new string('x', 2001);

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(PersistentEvent.Source)));
    }

    [Fact]
    public async Task Validate_WhenEventIsValid_ReturnsSuccess()
    {
        // Arrange
        var ev = CreateValidEvent();

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }

    [Fact]
    public async Task ValidateAsync_WhenEventIsValid_ReturnsSuccess()
    {
        // Arrange
        var ev = CreateValidEvent();

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(ev);

        // Assert
        Assert.True(isValid);
    }
}
