using Exceptionless.Core.Models;
using Exceptionless.Core.Validation;
using Xunit;

namespace Exceptionless.Tests.Validation;

public sealed class StackValidatorTests : TestWithServices
{
    private const string ValidObjectId = "123456789012345678901234";
    private readonly MiniValidationValidator _validator;

    public StackValidatorTests(ITestOutputHelper output) : base(output)
    {
        _validator = GetService<MiniValidationValidator>();
    }

    private Stack CreateValidStack()
    {
        return new Stack
        {
            Id = ValidObjectId,
            OrganizationId = ValidObjectId,
            ProjectId = ValidObjectId,
            Type = Event.KnownTypes.Error,
            SignatureHash = "abc123",
            SignatureInfo = new SettingsDictionary { { "key", "value" } },
            Title = "Test Stack"
        };
    }

    [Fact]
    public async Task Validate_WhenIdIsValidObjectId_ReturnsSuccess()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Id = ValidObjectId;

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }

    [Fact]
    public async Task Validate_WhenIdIsNull_ReturnsSuccess()
    {
        // Arrange — Id is auto-generated by repo, null means "not yet assigned"
        var stack = CreateValidStack();
        stack.Id = null!;

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData("12345678901234567890123")]
    [InlineData("1234567890123456789012345")]
    [InlineData("invalid-id")]
    [InlineData("")]
    public async Task Validate_WhenIdIsInvalid_ReturnsError(string id)
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Id = id;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.Id)));
    }

    [Fact]
    public async Task Validate_WhenOrganizationIdIsValidObjectId_ReturnsSuccess()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.OrganizationId = ValidObjectId;

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData("12345678901234567890123")]
    [InlineData("1234567890123456789012345")]
    [InlineData("invalid-id")]
    [InlineData("")]
    [InlineData(null)]
    public async Task Validate_WhenOrganizationIdIsInvalid_ReturnsError(string? organizationId)
    {
        // Arrange
        var stack = CreateValidStack();
        stack.OrganizationId = organizationId!;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.OrganizationId)));
    }

    [Fact]
    public async Task Validate_WhenProjectIdIsValidObjectId_ReturnsSuccess()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.ProjectId = ValidObjectId;

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData("12345678901234567890123")]
    [InlineData("1234567890123456789012345")]
    [InlineData("invalid-id")]
    [InlineData("")]
    [InlineData(null)]
    public async Task Validate_WhenProjectIdIsInvalid_ReturnsError(string? projectId)
    {
        // Arrange
        var stack = CreateValidStack();
        stack.ProjectId = projectId!;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.ProjectId)));
    }

    [Fact]
    public async Task Validate_WhenTitleExceedsMaxLength_ReturnsError()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Title = new string('a', 1001);

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.Title)));
    }

    [Fact]
    public async Task Validate_WhenTitleIsWithinMaxLength_ReturnsSuccess()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Title = new string('a', 1000);

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData("error")]
    [InlineData("log")]
    [InlineData("a")]
    public async Task Validate_WhenTypeIsValid_ReturnsSuccess(string? type)
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Type = type!;

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData(null)]
    public async Task Validate_WhenTypeIsNull_ReturnsError(string? type)
    {
        // Arrange — Stack.Type is [Required]: null is no longer valid (behavior change vs old FluentValidation).
        // A migration is needed to cleanup legacy stacks that may have null Type.
        var stack = CreateValidStack();
        stack.Type = type!;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.Type)));
    }

    [Fact]
    public async Task Validate_WhenTypeIsEmpty_ReturnsError()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Type = "";

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.Type)));
    }

    [Fact]
    public async Task Validate_WhenTypeExceedsMaxLength_ReturnsError()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Type = new string('a', 101);

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.Type)));
    }

    [Fact]
    public async Task Validate_WhenTypeIsWithinMaxLength_ReturnsSuccess()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Type = new string('a', 100);

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }


    [Theory]
    [InlineData("valid-tag")]
    public async Task Validate_WhenTagIsValid_ReturnsSuccess(string tag)
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Tags.Add(tag);

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData("")]
    [InlineData(null)]
    public async Task Validate_WhenTagIsEmpty_ReturnsError(string? tag)
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Tags.Add(tag);

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.Tags)));
    }

    [Fact]
    public async Task Validate_WhenTagExceedsMaxLength_ReturnsError()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Tags.Add(new string('a', 256));

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.Tags)));
    }

    [Fact]
    public async Task Validate_WhenTagIsWithinMaxLength_ReturnsSuccess()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.Tags.Add(new string('a', 255));

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }


    [Theory]
    [InlineData("hash")]
    public async Task Validate_WhenSignatureHashIsValid_ReturnsSuccess(string signatureHash)
    {
        // Arrange
        var stack = CreateValidStack();
        stack.SignatureHash = signatureHash;

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }

    [Theory]
    [InlineData("")]
    [InlineData(null)]
    public async Task Validate_WhenSignatureHashIsEmpty_ReturnsError(string? signatureHash)
    {
        // Arrange
        var stack = CreateValidStack();
        stack.SignatureHash = signatureHash!;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.SignatureHash)));
    }

    [Fact]
    public async Task Validate_WhenSignatureInfoIsNull_ReturnsError()
    {
        // Arrange
        var stack = CreateValidStack();
        stack.SignatureInfo = null!;

        // Act
        var (isValid, errors) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.False(isValid);
        Assert.Contains(errors.Keys, k => String.Equals(k, nameof(Stack.SignatureInfo)));
    }

    [Fact]
    public async Task Validate_WhenStackIsValid_ReturnsSuccess()
    {
        // Arrange
        var stack = CreateValidStack();

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }

    [Fact]
    public async Task ValidateAsync_WhenStackIsValid_ReturnsSuccess()
    {
        // Arrange
        var stack = CreateValidStack();

        // Act
        var (isValid, _) = await _validator.ValidateAsync(stack);

        // Assert
        Assert.True(isValid);
    }
}
