name: Elasticsearch 7.x Docker Image CI

on:
  push:
    paths:
    - 'build/docker/elasticsearch/7.x/**'
    - '.github/workflows/elasticsearch-docker-7.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v') != true

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.*
        #dotnet-quality: preview
    - name: Build Reason
      env:
        GITHUB_EVENT: ${{ toJson(github) }}
      run: "echo ref: ${{github.ref}} event: ${{github.event_name}}"
    - name: Build Version
      run: |
        dotnet tool install --global minver-cli --version 4.3.0
        version=$(minver --tag-prefix v)
        echo "MINVERVERSIONOVERRIDE=$version" >> $GITHUB_ENV
        echo "VERSION=$version" >> $GITHUB_ENV
        echo "### Version: $version" >> $GITHUB_STEP_SUMMARY
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64
    - name: Build custom Elasticsearch 7.x docker image
      working-directory: build/docker/elasticsearch/7.x
      run: |
        VERSION=$(sed -n 's/.*elasticsearch:\([^ ]*\).*/\1/p' Dockerfile)
        docker buildx build --platform linux/amd64,linux/arm64 --output "type=image,push=true" --file ./Dockerfile . --tag exceptionless/elasticsearch:$VERSION --tag exceptionless/elasticsearch:latest
